services:
  devnet:
    image: ghcr.io/ensdomains/contracts-v2:fix-docker-runtime-ci-arm
    command: ./script/runDevnet.ts --testNames
    pull_policy: always
    ports:
      - "8545:8545"
      - "8000:8000"
    environment:
      ANVIL_IP_ADDR: "0.0.0.0"
      ANVIL_CHAIN_ID: "1"
    healthcheck:
      test: ["CMD", "curl", "--fail", "-s", "http://localhost:8000/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
      start_interval: 1s
