packages:
  - packages/*
  - examples/*
minimumReleaseAge: 1440
trustPolicy: no-downgrade
trustPolicyExclude:
  - undici-types@6.21.0
strictPeerDependencies: false
linkWorkspacePackages: deep
autoInstallPeers: false
allowBuilds:
  esbuild: false
