export * from '../../actions/wallet/v2/deleteAlias.js'
export * from '../../actions/wallet/v2/grantResolverRoles.js'
export * from '../../actions/wallet/v2/grantRoles.js'
export * from '../../actions/wallet/v2/revokeRoles.js'
export * from '../../actions/wallet/v2/setAlias.js'
export * from '../../actions/wallet/v2/setResolver.js'
export * from '../../actions/wallet/v2/setSubregistry.js'
