const ROLE_REGISTRAR = 1n << 0n
const ROLE_REGISTRAR_ADMIN = ROLE_REGISTRAR << 128n

const ROLE_RENEW = 1n << 4n
const ROLE_RENEW_ADMIN = ROLE_RENEW << 128n

const ROLE_SET_SUBREGISTRY = 1n << 8n
const ROLE_SET_SUBREGISTRY_ADMIN = ROLE_SET_SUBREGISTRY << 128n

const ROLE_SET_RESOLVER = 1n << 12n
const ROLE_SET_RESOLVER_ADMIN = ROLE_SET_RESOLVER << 128n

const ROLE_SET_TOKEN_OBSERVER = 1n << 16n
const ROLE_SET_TOKEN_OBSERVER_ADMIN = ROLE_SET_TOKEN_OBSERVER << 128n

const ROLE_CAN_TRANSFER_ADMIN = (1n << 20n) << 128n

const ROLE_BURN = 1n << 24n
const ROLE_BURN_ADMIN = ROLE_BURN << 128n

export {
  ROLE_BURN,
  ROLE_BURN_ADMIN,
  ROLE_CAN_TRANSFER_ADMIN,
  ROLE_REGISTRAR,
  ROLE_REGISTRAR_ADMIN,
  ROLE_RENEW,
  ROLE_RENEW_ADMIN,
  ROLE_SET_RESOLVER,
  ROLE_SET_RESOLVER_ADMIN,
  ROLE_SET_SUBREGISTRY,
  ROLE_SET_SUBREGISTRY_ADMIN,
  ROLE_SET_TOKEN_OBSERVER,
  ROLE_SET_TOKEN_OBSERVER_ADMIN,
}
