name: Continuous Release
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm --filter @ensdomains/ensjs build

      - name: Publish ensjs to pkg.pr.new
        run: |
          cd ./packages/ensjs
          # remove prepack script for testing
          npm pkg delete scripts.prepack
          cd ../..
          pnpm dlx pkg-pr-new publish "./packages/ensjs"
