name: Continuous Release
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - uses: pnpm/action-setup@v6

      - uses: actions/setup-node@v7
        with:
          node-version: 24
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm -r --filter @ensdomains/ensjs-abi --filter @ensdomains/ensjs build

      - name: Publish to pkg.pr.new
        run: pnpm dlx pkg-pr-new publish "./packages/ensjs-abi" "./packages/ensjs"
